doctrine_mongodb:
  connections:
    default:
      server: '%env(DATABASE_URI)%'
      options: {}
  default_database: '%env(MONGODB_DB)%'
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          dir: '%kernel.project_dir%/src/Document'
          prefix: 'App\Document'
          alias: App