framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
                #default_middleware: allow_no_handlers
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
