framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            enroll_lecture:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/enroll_lecture'
                options:
                    exchange:
                        name: 'enroll_lecture'
                        type: direct
        routing:
            'Gwo\AppsRecruitmentTask\Application\Command\EnrollLectureCommand': enroll_lecture