version: '3.5'

services:
  app:
    build: ./
    container_name: apps-recruitment-task
    volumes:
      - .:/app:rw
    ports:
      - 0.0.0.0:10990:80/tcp
    depends_on:
      - database

  database:
    image: bitnami/mongodb:5.0.23
    container_name: apps-recruitment-task-database
    volumes:
      - mongodb:/bitnami/mongodb
    ports:
      - 27019:27017

volumes:
  mongodb:
