openapi: 3.0.1
info:
  title: GWO Apps Recruitment Task
  version: "0.1.0"
servers:
  - url: http://127.0.0.1:81
    description: Docker

paths:
  /api/login:
    $ref: "./paths/auths/login.yaml#/login"
  /api/lectures:
    $ref: "./paths/lectures/create_lecture.yaml#/createLecture"
  /api/lectures/{lectureUUID}/students/{studentUUID}:
    $ref: "./paths/lectures/delete_student.yaml#/deleteStudent"
  /api/lectures/{uuid}/enroll:
    $ref: "./paths/lectures/enroll_lecture.yaml#/enrollLecture"
  /api/students/lectures:
    $ref: "./paths/students/list_lectures.yaml#/listLectures"

