parameters:
    database_uri: '%env(DATABASE_URI)%'
    database_name: '%env(key:path:url:DATABASE_URI)%'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Gwo\AppsRecruitmentTask\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Gwo\AppsRecruitmentTask\Infrastructure\Persistence\MongoDB\DatabaseClient:
        $databaseUri: '%database_uri%'
        $databaseName: '%database_name%'

    Gwo\AppsRecruitmentTask\Application\Console\FillUserDataCommand:
        arguments:
            $databaseClient: '@Gwo\AppsRecruitmentTask\Infrastructure\Persistence\MongoDB\DatabaseClient'
            $passwordHasher: '@security.user_password_hasher'

    Gwo\AppsRecruitmentTask\Application\Query\Provider\MongoUserProvider:
        arguments:
            $databaseClient: '@Gwo\AppsRecruitmentTask\Infrastructure\Persistence\MongoDB\DatabaseClient'
            $passwordHasher: '@security.user_password_hasher'

    Gwo\AppsRecruitmentTask\Domain\Security\Voter\LectureCreateVoter:
        tags: ['security.voter']

    Gwo\AppsRecruitmentTask\Domain\Security\Voter\LectureEnrollVoter:
        tags: ['security.voter']

    Gwo\AppsRecruitmentTask\Application\CommandHandler\CreateLectureCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'command.bus' }

    Gwo\AppsRecruitmentTask\Application\CommandHandler\EnrollLectureCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'command.bus' }

#    Gwo\AppsRecruitmentTask\Domain\Exception\CustomExceptionListener:
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception }
