api_create_lectures:
  path: /api/lectures
  controller: Gwo\AppsRecruitmentTask\Presentation\Controller\CreateLectureController::create
  methods: [POST]

api_enroll_lectures:
  path: /api/lectures/{uuid}/enroll
  controller: Gwo\AppsRecruitmentTask\Presentation\Controller\EnrollLectureController::enroll
  methods: [ POST ]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'
