name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        mongodb:
            image: mongo:8
            ports:
                - "27017:27017"
    env:
        DATABASE_URI: 'mongodb://localhost:27017/apps-recruitment-task'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql, intl, bcmath
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader   
          
      - name: Run Symfony console commands
        run: |
          php bin/console doctrine:mongodb:schema:create
          php bin/console cache:clear
                
      - name: Run console commnad
        run: |
          php bin/console app:fill-user-data
          php bin/console cache:clear
  
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

